export enum LocationPlaceOfServiceKind {
  Clinic = "Clinic",
  DriveThru = "Drive-thru",
  EmergencyRoom = "Hospital",
  Fqhc = "Health Center",
  HealthCenter = "Health Center",
  Hospital = "Hospital",
  ImmediateCare = "Urgent Care",
  MedicalCenter = "Medical Center",
  Other = "Other",
  PrimaryCare = "Primary Care",
  PrivateLab = "Commercial Lab",
  PublicHealthDepartment = "Public Health Site",
  Retail = "Retail/Store",
  Temporary = "Temporary/Popup",
  UrgentCare = "Urgent Care",
};
